#include "Cheval.h"




void Cheval::hennit()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:0000000000000898 begin
{
}
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:0000000000000898 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
