#include "Oiseau.h"




void Oiseau::vole()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:000000000000089F begin
{
}
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:000000000000089F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
