#include "Animal.h"




void Animal::dispName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:000000000000086E begin
{
}
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:000000000000086E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Animal::dispCarac()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:0000000000000870 begin
{
}
// section -64--88--128-77--6fe5cfea:1573d9cbde0:-8000:0000000000000870 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
